# Site settings
title: DevMine
owner: The DevMine authors
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devmine.ch" # the base hostname & protocol for your site
github_username:  DevMine

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

highlighter: rouge

exclude: [Makefile]
