# Site settings
title: DevMine
owner: The DevMine authors
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    DevMine - An open source project to evaluate developers skills based on their open-source contributions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devmine.ch" # the base hostname & protocol for your site
github_username:  DevMine

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

highlighter: rouge

exclude: [Makefile, README.md]
