# Site settings
title: DevMine
owner: The DevMine authors
email: contact@devmine.ch
description: > # this means to ignore newlines until "baseurl:"
    DevMine - A developer search engine and source code analysis framework
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devmine.ch" # the base hostname & protocol for your site
github_username:  DevMine

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

highlighter: rouge

exclude: [Makefile, README.md]

permalink: /news/:year/:month/:day/:title/

defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
